version: '3.8'
services:
  foodloop-postgres:
    image: "postgres:16.1-alpine"
    container_name: foodloop-postgres
    volumes:
      - ./foodloop-data:/lib/postgresql/data
      - ./foodloop-db-files/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./foodloop-db-files/seeders/02_insertFood.sql:/docker-entrypoint-initdb.d/02_insertFood.sql
      - ./foodloop-db-files/seeders/04_insertFoodToTag.sql:/docker-entrypoint-initdb.d/04_insertFoodToTag.sql
      - ./foodloop-db-files/seeders/05_insertRestaurant.sql:/docker-entrypoint-initdb.d/05_insertRestaurant.sql
      - ./foodloop-db-files/seeders/06_insertRestaurantToFood.sql:/docker-entrypoint-initdb.d/06_insertRestaurantToFood.sql
      - ./foodloop-db-files/seeders/07_insertRestaurantToTag.sql:/docker-entrypoint-initdb.d/07_insertRestaurantToTag.sql
      - ./foodloop-db-files/seeders/03_insertTag.sql:/docker-entrypoint-initdb.d/03_insertTag.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
