version: '3.8'
services:
  foodloop-postgres:
    image: "postgres:16.1-alpine"
    container_name: foodloop-postgres
    volumes:
      - ./foodloop-data:/var/lib/postgresql/data
      - ./foodloop-db-files/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped