INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Chilli Crab', 'Wok-fried crab in a spicy, tangy tomato-based sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Black Pepper Prawns', 'Juicy prawns stir-fried with aromatic black pepper.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Salted Egg Calamari', 'Crispy calamari coated in rich salted egg yolk sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Hokkien Mee', 'Stir-fried noodles with prawns, squid, and a savory seafood broth.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Dragon Roll', 'Eel, avocado, and cucumber topped with thin avocado slices.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Rainbow Sashimi Platter', 'Assorted sashimi slices artfully arranged for a burst of colors.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Volcano Maki', 'Spicy tuna, avocado, and tempura flakes, baked to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Matcha Cheesecake', 'A delightful fusion of Japanese matcha and creamy cheesecake.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Chicken Tikka Masala', 'Grilled chicken in a creamy and aromatic tomato-based curry.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Paneer Butter Masala', 'Soft paneer cubes in a luscious buttery tomato sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Garlic Naan', 'Tandoor-baked flatbread with a fragrant garlic topping.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Lassi', 'A refreshing yogurt drink blended with sweet mango puree.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Ayam Buah Keluak', 'Chicken in a rich, earthy sauce made with buah keluak nuts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Nyonya Laksa', 'Spicy coconut milk soup with prawns, chicken, and rice noodles.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kueh Lapis', 'Layered steamed cake with vibrant colors and fragrant pandan.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cendol', 'A traditional dessert with pandan jelly, red beans, and coconut milk.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Har Gow', 'Steamed shrimp dumplings with a translucent wrapper.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Xiao Long Bao', 'Delicate soup dumplings filled with savory broth and pork.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Peking Duck Rolls', 'Crispy duck rolls with hoisin sauce and fresh veggies.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Pomelo Sago', 'A refreshing dessert with mango, pomelo, and sago pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pad Thai Goong', 'Stir-fried rice noodles with prawns, tofu, and peanuts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tom Yum Noodle Soup', 'Spicy and sour noodle soup with lemongrass and lime.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Green Curry Chicken', 'A fragrant green curry with tender chicken and Thai basil.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Sticky Rice', 'Sweet sticky rice topped with ripe mango slices and coconut milk.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Bibimbap', 'Mixed rice bowl with vegetables, gochujang, and a fried egg.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kimchi Jjigae', 'Spicy kimchi stew with pork, tofu, and vegetables.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Korean BBQ Bulgogi', 'Marinated and grilled beef, served with ssamjang sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Bingsu Delight', 'Shaved ice dessert topped with sweet red beans, fruit, and condensed milk.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Hainanese Chicken Rice Pizza', 'A fusion pizza with the flavors of Hainanese Chicken Rice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Laksa Pasta', 'Spaghetti in a rich and spicy laksa-inspired sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Chilli Crab Tacos', 'Soft tacos filled with succulent Chilli Crab meat and crispy shell.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Durian Cheesecake', 'A decadent cheesecake infused with the distinctive aroma of durian.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pho Bo', 'Beef noodle soup with aromatic herbs and spices.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Banh Mi Thit', 'Crusty baguette filled with savory grilled pork and fresh veggies.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Goi Cuon', 'Fresh spring rolls with shrimp, herbs, and vermicelli noodles.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Vietnamese Iced Coffee', 'Strong and sweet coffee with condensed milk, served over ice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Greek Salad', 'A refreshing salad with tomatoes, cucumbers, olives, and feta cheese.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Seafood Paellas', 'Saffron-infused rice with a medley of fresh seafood.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Caprese Pizza', 'Wood-fired pizza topped with tomatoes, mozzarella, and basil.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Blissa', 'Layers of phyllo pastry, nuts, and honey in a sweet and sticky delight.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tacos Al Pastor', 'Marinated pork tacos with pineapple, onions, and cilantro.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Guacamole with Chips', 'Creamy avocado dip served with crispy tortilla chips.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Enchiladas Suizas', 'Chicken enchiladas topped with green tomatillo sauce and melted cheese.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Margarita Madness', 'Classic margarita with a salted rim and a zesty kick.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Doner Kebab Deluxe', 'Spit-roasted meat, veggies, and yogurt sauce in a warm flatbread.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Moussaka Royale', 'Layered casserole with eggplant, minced meat, and béchamel sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Turkish Delight Platter', 'Assorted flavors of sweet Turkish delight, a true indulgence.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Symphony', 'An orchestra of flaky layers, nuts, and honey in a dazzling baklava dessert.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Dim Sum Platter', 'A selection of delicate dim sum, perfect for sharing.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Roast Duck Extravaganza', 'Crispy-skinned duck with succulent meat and a flavorful hoisin glaze.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Sweet and Sour Prawns', 'Juicy prawns in a tangy sweet and sour sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Egg Custard Tart', 'Flaky pastry filled with silky smooth egg custard.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Picanha Skewers', 'Prime sirloin beef skewers, grilled to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Feijoada Feasts', 'A hearty stew of black beans, pork, and sausage.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Coxinha Delight', 'Deep-fried dough filled with shredded chicken, a Brazilian favorite.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Brigadeiro Bonanza', 'Chocolate truffles rolled in sprinkles, a sweet ending to your meal.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pad Thai Perfection', 'Classic Thai stir-fried noodles with prawns, tofu, and peanuts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Ramen Reverie', 'Japanese ramen with savory broth, noodles, and a medley of toppings.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Char Kway Teow Temptation', 'Stir-fried flat rice noodles with prawns, Chinese sausage, and egg.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pho Fusion', 'Vietnamese noodle soup with beef, fresh herbs, and a fragrant broth.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mai Tai Bliss', 'A tropical cocktail with rum, lime, and orgeat syrup.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Poke Bowl Delight', 'A bowl of fresh raw fish, veggies, and rice in a Hawaiian-inspired dish.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kalua Pork Luau', 'Slow-cooked shredded pork with a smoky flavor.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Haupia Pie Dream', 'Coconut cream pie with a silky haupia layer, a true tropical treat.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Seafood Souvlaki', 'Grilled skewers of mixed seafood marinated in Mediterranean herbs.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Moussaka Marvel', 'Layered casserole with eggplant, minced meat, and béchamel sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Octopus Odyssey', 'Tender grilled octopus with olive oil, lemon, and herbs.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Bliss', 'Layers of phyllo pastry, nuts, and honey in a sweet and sticky delight.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Chilli Crab Ravioli', 'Fresh pasta parcels filled with succulent crab meat, drenched in a spicy chilli crab sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Hainanese Laksa Pizza', 'A fusion of Italian and Peranakan flavors on a thin-crust pizza, topped with laksa-infused broth and seafood.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Satay Skewer Tacos', 'Juicy satay skewers served in soft taco shells, topped with peanut sauce and cucumber salsa.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kaya Coconut Cupcakes', 'Delicate coconut-flavored cupcakes filled with kaya (coconut and egg jam), topped with a pandan leaf frosting.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Sushi Burger Trio', 'Mini burger with sushi rice buns, filled with sashimi slices and drizzled with special Tokyo sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Matcha Tempura Ice Cream', 'Tempura-battered matcha ice cream, served with a side of red bean paste and green tea sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Okonomiyaki Fries', 'Crispy fries topped with layers of Japanese-style pancake, bonito flakes, and okonomiyaki sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Yuzu Sake Sorbet', 'A refreshing sorbet made with yuzu and sake, served in a sake-infused ice bowl.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Butter Chicken Tacos', 'Soft tacos filled with succulent butter chicken, topped with mint chutney and pickled onions.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Lassi Panna Cotta', 'Creamy panna cotta infused with the flavors of mango lassi, served with a cardamom shortbread cookie.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Biryani Spring Rolls', 'Crispy spring rolls filled with fragrant biryani rice, served with raita dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Chai Spiced Creme Brulee', 'Classic creme brulee infused with the warm spices of Indian chai, caramelized to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Nyonya Otak-Otak Sliders', 'Mini sliders featuring grilled fish cakes with aromatic Nyonya otak-otak paste.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kueh Sampler Platter', 'Assorted traditional Peranakan kueh, including kueh lapis, ondeh-ondeh, and kueh dadar.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Ayam Buah Keluak Curry', 'A rich and flavorful curry made with chicken and the unique buah keluak nut.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Durian Penguin Parfait', 'Layered parfait with creamy durian pengat, gula melaka syrup, and coconut crumble.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Har Gow Dumplings', 'Steamed crystal shrimp dumplings, showcasing the culinary artistry of Cantonese dim sum.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Peking Duck Spring Rolls', 'Crispy spring rolls filled with slices of Peking duck, accompanied by hoisin sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Wok-Tossed Black Pepper Beef', 'Tender strips of beef stir-fried with black pepper sauce, bell peppers, and onions.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Double-Boiled Snow Fungus Soup', 'A nourishing soup with snow fungus, red dates, and goji berries, double-boiled to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tom Yum Noodle Bowl', 'A comforting bowl of spicy and tangy tom yum broth with rice noodles and fresh herbs.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Green Curry Sea Bass', 'Grilled sea bass fillet smothered in aromatic green curry sauce, served with jasmine rice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Som Tum Salad Rolls', 'Fresh salad rolls filled with green papaya, carrot, and Thai herbs, served with peanut dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Sticky Rice Parfait', 'A deconstructed parfait featuring layers of mango sticky rice, coconut cream, and crunchy mung beans.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Meze Platter', 'A selection of classic Turkish mezes, including hummus, babaganoush, and dolma.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Iskender Kebab Pizza', 'Thin-crust pizza topped with Iskender kebab slices, yogurt, and tomato sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Sundae', 'Layers of flaky baklava, vanilla ice cream, and pistachio crumble, drizzled with honey.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Turkish Delight Martini', 'A sweet and fragrant martini inspired by the flavors of Turkish delight.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Guacamole Fiesta Nachos', 'Crispy nachos piled high with guacamole, pico de gallo, black beans, and melted cheese.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tacos Al Pastor Trio', 'Soft tacos filled with marinated and grilled pork, pineapple salsa, and cilantro.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Enchilada Verdes', 'Chicken enchiladas topped with green tomatillo sauce, sour cream, and queso fresco.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Churros with Spicy Chocolate Sauce', 'Golden churros served with a side of spicy Mexican chocolate dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pad Thai Noodles', 'Stir-fried rice noodles with shrimp, tofu, bean sprouts, and peanuts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Ramen Fusion Bowl', 'A fusion of Japanese and Korean flavors with ramen noodles, kimchi, and miso broth.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Char Kway Teow Stir-Fry', 'Flat rice noodles stir-fried with prawns, Chinese sausage, and egg.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pho Ga Noodle Soup', 'Vietnamese chicken noodle soup with aromatic herbs and rice noodles.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Greek Salad Tartlet', 'Crispy tartlet filled with Greek salad ingredients, feta cheese, and olives.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Seafood Paella', 'A classic Spanish paella with a medley of seafood, saffron-infused rice, and chorizo.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Margherita Pita Pizza', 'Pita bread topped with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tiramisu Mousse Cup', 'Layers of coffee-soaked ladyfingers, mascarpone mousse, and cocoa dust in a bite-sized cup.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Banh Mi Burger', 'A fusion of Vietnamese banh mi and a classic burger, featuring a lemongrass-infused patty.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pho Bo Noodle Bowl', 'Beef pho with rice noodles, tender slices of beef, and fragrant herbs.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Goi Cuon Spring Rolls', 'Fresh rice paper rolls filled with shrimp, vermicelli noodles, and herbs, served with peanut sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Vietnamese Iced Coffee Affogato', 'Creamy vanilla ice cream drowned in strong Vietnamese iced coffee, topped with condensed milk.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Picanha Steak Skewer', 'Tender skewers of top sirloin, seasoned with Brazilian spices and grilled to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Feijoada Feas', 'A hearty Brazilian stew with black beans, pork, sausages, and beef, served with rice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Coxinha de Franga', 'Golden-fried dough filled with shredded chicken and cream cheese, a popular Brazilian snack.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Brigadeiro Truffle Platter', 'Assorted brigadeiro truffles in flavors like traditional chocolate, coconut, and pistachio.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Poke Bowl Paradise', 'A colorful bowl featuring fresh tuna, salmon, mango, avocado, and tropical fruits.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kalua Pork Sliders', 'Slow-cooked and shredded Kalua pork sliders with pineapple slaw on soft Hawaiian rolls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mai Tai Mocktail', 'A refreshing non-alcoholic version of the classic Mai Tai, featuring tropical fruit juices and grenadine.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Haupia Coconut Pie', 'A creamy coconut custard pie with a macadamia nut crust, a taste of the Hawaiian islands.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Seafood Souvlaki Platter', 'Grilled skewers with a variety of marinated seafood, served with tzatziki sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Moussaka Tower', 'Layers of eggplant, potatoes, minced lamb, and béchamel sauce baked to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Octopus Salad', 'Tender octopus marinated in olive oil, lemon, and herbs, served with a Greek salad.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Cheesecake', 'A fusion of classic New York cheesecake with layers of honey-soaked baklava on top.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Chilli Crab Spring Rolls', 'Crispy spring rolls filled with succulent crab meat and a spicy chilli crab sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Hainanese Laka Pizza', 'A unique pizza featuring Hainanese laksa flavors with prawns, bean sprouts, and laksa broth.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Nasi Lemak Sushi Rolls', 'Sushi rolls filled with fragrant coconut rice, sambal prawns, and anchovies.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Durian Panna Cotta', 'Smooth panna cotta infused with the distinctive taste of durian, topped with caramel sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Sushi Tacos', 'Tacos filled with fresh sashimi, avocado, and wasabi mayo, served in a crispy nori shell.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Matcha Tempura Udon', 'Udon noodles in a savory matcha-infused broth, topped with crispy tempura and green onions.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Teriyaki Soba Salad', 'A refreshing soba noodle salad with teriyaki-glazed chicken, mixed greens, and sesame dressing.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Yuzu Cheesecake Mochi', 'Soft mochi filled with creamy yuzu-flavored cheesecake filling, dusted with powdered sugar.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Masala Wonton Dumplings', 'Wonton dumplings filled with spiced masala chicken, served with a tangy tamarind dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Nasi Goreng Curry Bowl', 'A fusion of Indonesian nasi goreng and Indian curry, with fried rice, curry sauce, and a fried egg.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Paneer Satay Skewers', 'Grilled skewers featuring marinated paneer, served with a peanut satay sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cardamom Chai Tiramisu', 'A delightful twist on tiramisu infused with the flavors of aromatic cardamom and chai.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Nyonya Laksa Tart', 'A savory tart featuring the bold flavors of Nyonya laksa, with prawns, fish cakes, and coconut broth.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Otak-Otak Stuffed Chicken', 'Chicken breast stuffed with spicy otak-otak paste, grilled to perfection and served with sambal.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kueh Rainbow Tower', 'A colorful tower of assorted traditional kueh, each layer representing a different Peranakan delight.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Durian Pengat Parfait', 'Layers of durian pengat, gula melaka, and coconut cream in a parfait glass, topped with crispy coconut flakes.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Har Gow Crystal Dumplings', 'Transparent dumplings filled with succulent shrimp, showcasing the delicate art of dim sum.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Peking Duck Bao Sliders', 'Soft bao sliders filled with crispy Peking duck, hoisin sauce, and shredded scallions.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Black Bean Chicken Feet', 'Chicken feet marinated in black bean sauce and steamed to perfection, a classic dim sum delicacy.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Double-Boiled Birds Nest Soup', 'A nourishing soup made with double-boiled birds nest, ginseng, and premium chicken broth.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tom Yum Sushi Rolls', 'Sushi rolls filled with tom yum-infused seafood, herbs, and a touch of Thai chili.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Green Curry Roti Tacos', 'Roti tacos filled with aromatic green curry, coconut chicken, and Thai basil.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Som Tum Papaya Salad Cup', 'Individual cups of refreshing Som Tum salad with green papaya, cherry tomatoes, and peanuts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Sticky Rice Bites', 'Bite-sized portions of mango sticky rice, perfect for a sweet and satisfying ending.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Meze Platter Extravaganza', 'A generous platter of assorted mezes, including hummus, babaganoush, and dolma.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Lamb Kofta Kebab Pide', 'Turkish pide topped with succulent lamb kofta, tomatoes, and red onions.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Ice Cream Sundae', 'Layers of baklava, vanilla ice cream, and pistachio crumble, drizzled with honey.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Turkish Delight Martin', 'A tempting martini infused with the sweet and fragrant flavors of Turkish delight.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Guacamole Explosion Nachos', 'Crispy nachos topped with a generous serving of guacamole, pico de gallo, and melted cheese.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Taco Trio Al Pastor', 'Soft tacos filled with marinated pork al pastor, pineapple salsa, and cilantro.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Enchilada Verdes Supreme', 'Chicken enchiladas smothered in green tomatillo sauce, sour cream, and queso fresco.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Churros Con Chocolate Fondue', 'Golden churros served with a rich and velvety chocolate fondue for dipping.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pad Thai Ramen Fusion', 'A fusion of Pad Thai and ramen, combining stir-fried noodles, prawns, tofu, and peanuts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Char Kway Teow Udon Bowl', 'Udon noodles stir-fried with prawns, Chinese sausage, and egg, in the style of char kway teow.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pho Ga Noodle Salad', 'Vietnamese-inspired salad with rice noodles, chicken, fresh herbs, and nuoc cham dressing.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Miso Laksa Fusion Soup', 'A harmonious blend of Japanese miso soup and Singaporean laksa, with tofu, seaweed, and laksa broth.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Caprese Bruschetta', 'Toasted bruschetta topped with ripe tomatoes, fresh mozzarella, basil, and a balsamic glaze.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Seafood Paella Platter', 'A generous platter of classic Spanish paella with a medley of seafood, saffron-infused rice, and chorizo.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pesto Hummus Mezze Board', 'A mezze board featuring hummus infused with the flavors of basil pesto, served with pita and vegetables.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tiramisu Baklava Parfait', 'Layers of tiramisu and baklava, creating a luscious parfait with coffee-soaked ladyfingers and honeyed nuts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Banh Mi Burger Bliss', 'A fusion of Vietnamese banh mi and a classic burger, featuring lemongrass-infused pork or tofu.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pho Bo Noodle Bow', 'Beef pho with rice noodles, tender slices of beef, and fragrant herbs.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Goi Cuon Fresh Rolls', 'Fresh rice paper rolls filled with shrimp, vermicelli noodles, herbs, and peanut dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Vietnamese Iced Latte Affogato', 'Creamy vanilla ice cream drowned in strong Vietnamese iced coffee, topped with condensed milk.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Picanha Steak Skewers', 'Tender skewers of top sirloin, seasoned with Brazilian spices and grilled to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Feijoada Feast', 'A hearty Brazilian stew with black beans, pork, sausages, and beef, served with rice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Coxinha de Frango', 'Golden-fried dough filled with shredded chicken and cream cheese, a popular Brazilian snack.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Brigadeiro Truffle Platters', 'Assorted brigadeiro truffles in flavors like traditional chocolate, coconut, and pistachio.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Butter Chicken Pizza', 'Thin-crust pizza topped with tender butter chicken, mozzarella, and fresh cilantro.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Masala Waffle Sandwich', 'Waffle sandwiches filled with spiced chickpeas, chutney, and mixed greens.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Nawabi Biryani Bowl', 'Fragrant biryani with basmati rice, marinated chicken, and aromatic spices.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Gulab Jamun Milkshake', 'A sweet and indulgent milkshake featuring the classic Indian dessert, gulab jamun.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Sashimi Symphony Platter', 'An exquisite platter featuring a variety of fresh sashimi slices.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Matcha Tempura Froyo', 'Tempura-battered matcha ice cream, served with a drizzle of honey.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Teriyaki Temptation Bento', 'Bento box with teriyaki chicken, sushi rolls, and seaweed salad.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mochi Madness Sampler', 'Assorted mochi with unique fillings, including red bean, green tea, and mango.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Ayam Rendang Nasi Lemak', 'Nasi lemak served with aromatic Ayam Rendang, anchovies, and sambal.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pineapple Tamarind Prawns', 'Stir-fried prawns in a sweet and tangy pineapple-tamarind sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kueh Lapis Tower', 'Layers of colorful kueh lapis, a traditional Nyonya steamed cake.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cendol Delight Sundae', 'A refreshing sundae featuring cendol, coconut milk, and gula melaka syrup.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Steamed Halal Dim Sum Platter', 'An assortment of steamed dumplings with chicken, shrimp, and vegetables.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Siew Mai Sliders', 'Mini sliders filled with succulent siew mai, served with chili sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baked Char Siew Puffs', 'Flaky pastry filled with sweet and savory Halal char siew filling.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Pomelo Sago Dessert', 'A refreshing dessert with mango, pomelo, sago pearls, and coconut milk.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Shawarma Feast Platter', 'A grand platter featuring chicken and beef shawarma, hummus, and falafel.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Moussaka Towers', 'Layers of eggplant, minced lamb, and béchamel sauce baked to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Blis', 'Layers of flaky baklava with pistachios, honey, and rosewater.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Turkish Coffee Elixir', 'A rich and aromatic cup of Turkish coffee, a perfect way to end the meal.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Chilli Crab', 'Fresh crab cooked in a savory and spicy tomato-based chili sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Salted Egg Prawn Tempura', 'Prawns coated in a crispy salted egg batter, served with tangy lime mayo.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Black Pepper Crab Fried Rice', 'Fried rice with wok-tossed black pepper crab meat, vegetables, and a hint of spice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Durian Creme Brulee', 'A fusion dessert combining the creamy texture of creme brulee with the unique flavor of durian.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tom Yum Seafood Hot Pot', 'A comforting hot pot with a spicy and tangy Tom Yum broth, loaded with seafood.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Green Curry Chicken Pie', 'Flaky pastry filled with aromatic green curry chicken and Thai basil.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Som Tum Papaya Salad Rolls', 'Fresh spring rolls filled with Som Tum papaya salad, grilled chicken, and herbs.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Sticky Parfait', 'Layers of mango sticky rice, coconut cream, and toasted sesame seeds in a parfait glass.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Greek Salad Flatbread', 'Flatbread topped with a fresh Greek salad, feta cheese, and olive tapenade.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Seafood Paella', 'A flavorful paella with Halal chicken, seafood, saffron-infused rice, and chorizo.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Caprese Hummus Platter', 'Hummus topped with cherry tomatoes, fresh mozzarella, and basil.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Baklava Cheesecake Bites', 'Mini cheesecake bites with layers of baklava, honey, and crushed pistachios.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Bibimbap Bonanza', 'A customizable bibimbap bowl with a choice of Halal beef, chicken, or tofu.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Kimchi Pancake Delight', 'Crispy pancakes filled with kimchi and served with a soy dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Korean Fried Chicken Bites', 'Crispy fried chicken bites tossed in a sweet and spicy gochujang sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Green Tea Bingsu Bliss', 'Shaved ice dessert topped with green tea syrup, red bean, and mochi.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Picanha Steak Skewers', 'Tender skewers of top sirloin, seasoned with Brazilian spices and grilled to perfection.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Feijoada Feast', 'A hearty Halal Brazilian stew with black beans, Halal beef, sausages, and turkey, served with rice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Coxinha de Frango', 'Golden-fried dough filled with shredded Halal chicken and cream cheese, a popular Brazilian snack.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Brigadeiro Truffle Platter', 'Assorted Halal brigadeiro truffles in flavors like traditional chocolate, coconut, and pistachio.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Tango Chicken Wrap', 'Grilled chicken wrap with mango salsa, lettuce, and a zesty lime dressing.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Coconut Lemongrass Shrimp Bowl', 'A bowl of succulent shrimp in a coconut lemongrass sauce, served with jasmine rice.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pineapple Tiramisu Parfait', 'Layers of pineapple-infused tiramisu with mascarpone cream and sponge cake.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Lychee Mojito Mocktail', 'A refreshing non-alcoholic mojito with lychee, mint, and lime.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Lamb Tagine', 'Slow-cooked Halal lamb tagine with apricots, almonds, and a blend of Moroccan spices.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Couscous Royale', 'Couscous served with Halal chicken, merguez sausages, vegetables, and harissa sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Falafel Wrap', 'Warm flatbread filled with crispy Halal falafel, tahini sauce, and pickled vegetables.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Mint Tea Elixir', 'A refreshing and aromatic glass of traditional Moroccan mint tea.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Ceviche Medley', 'A medley of fresh seafood ceviche with lime, chili, and Peruvian corn.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Lomo Saltado Burrito', 'A burrito filled with Halal lomo saltado, rice, beans, and Peruvian salsa.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Aji de Gallina Empanadas', 'Empanadas filled with shredded Halal chicken in a creamy aji de gallina sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Chicha Morada Sorbet', 'Sorbet made with Halal chicha morada, a traditional Peruvian purple corn drink.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Chicken Rice Bowl', 'Tender slices of Halal chicken served on a bed of fragrant chicken rice, with ginger and chili sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Laksa Lemak Noodles', 'Creamy coconut laksa noodles with prawns, fish cakes, and bean sprouts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Char Kway Teow Stir-Fry', 'Stir-fried flat rice noodles with Halal chicken, prawns, Chinese sausage, and egg.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Ice Kachang Delight', 'Shaved ice dessert with a medley of colorful toppings, red beans, and sweet syrup.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Banh Mi Burger', 'A fusion of Vietnamese banh mi and a classic burger, featuring lemongrass-infused Halal chicken.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Nasi Goreng Spring Rolls', 'Spring rolls filled with Halal nasi goreng, chicken, and a sweet soy dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Murtabak Wraps', 'Flaky wraps filled with spiced Halal chicken, eggs, and a tangy curry dipping sauce.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Bubble Tea Fusion', 'A creative fusion of Halal bubble tea with unique flavors and toppings.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Signature Chai Latte', 'Rich and aromatic chai latte with a layer of creamy foam, perfect for tea enthusiasts.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Lychee Rose Burst', 'Delicate rose tea infused with sweet lychee, complemented by lychee bursting pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Matcha Madness Supreme', 'Premium matcha green tea blended with red bean and topped with matcha-infused whipped cream.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Delight Special', 'An exclusive halal option featuring a refreshing mix of tropical fruits and coconut jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Classic Milk Tea Delight', 'Smooth black tea blended with creamy milk and chewy tapioca pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Peach Paradise Fusion', 'Peach-infused green tea with a burst of fruity flavors, topped with peach caviar pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Oriental Jasmine Elixir', 'Fragrant jasmine tea with crystal boba pearls, creating a delightful floral experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Harmony Medley', 'A specially crafted halal option featuring a mix of exotic fruits and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Golden Caramel Velvet', 'Velvety caramel milk tea with golden pearls, providing a rich and indulgent treat.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Dragonfruit Fantasy Fizz', 'Dragonfruit-infused sparkling tea with popping dragonfruit pearls for a burst of freshness.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Hazelnut Symphony Swirl', 'A symphony of hazelnut flavors in this delightful hazelnut milk tea with hazelnut boba.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Heaven Elixir', 'An exclusive halal elixir featuring floral notes, lychee bubbles, and coconut jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Passionfruit Paradise', 'Passionfruit green tea with a burst of passionfruit pearls, creating a tropical escape.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Tango Delight', 'A delightful dance of mango flavors in this mango milk tea with mango boba and jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Coconut Calypso Crush', 'Creamy coconut milk tea with coconut jelly and a sprinkle of shredded coconut.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Tropics Bliss', 'A halal-certified blend featuring a medley of tropical fruits and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Serenity Jasmine Green', 'Jasmine green tea with a touch of tranquility, topped with jasmine-infused pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('ZenGinger Infusion', 'A calming ginger tea infusion with honey, perfect for a soothing and refreshing experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Blueberry Zen Burst', 'Blueberry black tea with a burst of blueberry pearls, creating a zen-inspired delight.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Serenity Soother', 'A halal-certified blend featuring calming chamomile, floral notes, and lychee pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Tango Surprise', 'Surprisingly sweet mango tea with a burst of mango boba pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cookies & Cream Dream', 'Decadent cookies and cream milk tea with cookie crumble and cream cheese foam.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Taro Temptation Elixir', 'A tempting taro milk tea with taro boba pearls for a delightful chew.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Delightful Fusion', 'A halal-certified fusion featuring a mix of fruity flavors, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Classic Pearl Milk Tea', 'The timeless classic, black milk tea with chewy tapioca pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Strawberry Fields Fizz', 'Sparkling strawberry tea with strawberry boba pearls for a fruity burst.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Pineapple Coconut Crush', 'Tropical pineapple coconut green tea with coconut jelly and a hint of pineapple boba.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Harbor Delight', 'An exclusive halal blend featuring refreshing fruits, aloe vera, and lychee pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Strawberry Kiwi Burst', 'A burst of strawberry and kiwi flavors in this delightful fruit tea with popping pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Brown Sugar Boba Bliss', 'Rich brown sugar milk tea with a layer of creamy foam and caramelized boba pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Lemonade Fizz Pop', 'Sparkling lemonade tea with popping lychee pearls for a refreshing pop.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Bursting Medley', 'A halal-certified medley featuring a mix of exotic fruits, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Honeydew Melody Medley', 'Sweet honeydew green tea with a melody of honeydew pearls and coconut jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Tropical Tango Tonic', 'A tropical tonic of passionfruit and mango tea with a burst of tropical pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Caramel Swirl Sensation', 'Creamy caramel milk tea with a swirl of caramel syrup and brown sugar boba.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Harmony Symphony', 'An exclusive halal-certified symphony featuring a blend of calming chamomile, lychee pearls, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Blueberry Blessing Burst', 'Blueberry-infused tea with a burst of blueberry pearls, creating a delightful blessing.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Matcha Divine Delight', 'Divinely rich matcha milk tea with red bean and matcha-infused whipped cream.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cocoa Serenity Sip', 'A serene sip of cocoa milk tea with chocolate boba pearls for a heavenly experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Blessings Blend', 'A halal-certified blend featuring a mix of tropical fruits, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Rose Petal Elegance', 'Elegant rose tea with floral notes, adorned with rose petals and crystal boba pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Passionfruit Fusion Fizz', 'Passionfruit green tea with a fizzy twist and popping passionfruit pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Lavender Lemonade Love', 'Lavender-infused lemonade tea with a hint of sweetness, topped with lavender boba.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Hue Medley', 'A halal-certified medley featuring a mix of fruity flavors, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Strawberry Burst Bites', 'A burst of strawberry flavors with strawberry boba and strawberry-flavored popping pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Peachy Keen Delight', 'Peach-infused milk tea with peach chunks, cream cheese foam, and peach boba.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Blueberry Bite Explosion', 'Blueberry black tea with a burst of blueberry pearls and blueberry-flavored popping pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Blissful Bites', 'A halal-certified blend featuring a mix of tropical fruits, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Tango Groove', 'Groovy mango tea with a dance of mango boba pearls and mango jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Jasmine Jazz Harmony', 'Smooth jasmine green tea with a jazz of jasmine-infused pearls and coconut jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cocoa Cha-Cha Chill', 'A chill blend of cocoa milk tea with a cha-cha of chocolate boba pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Groovy Medley', 'An exclusive halal-certified medley featuring a mix of fruity flavors, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Classic Earl Grey Elixir', 'An elixir of classic Earl Grey tea with creamy foam and chewy tapioca pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mango Mania Fusion', 'A fusion of mango flavors in this mango milk tea with mango boba pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Green Apple Orchid Oasis', 'Green apple-infused tea with orchid petals and a burst of green apple pearls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Barn Bliss', 'A halal-certified blend featuring a mix of tropical fruits, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Peach Blossom Bliss', 'Peach blossom green tea with a blissful mix of peach boba and coconut jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Lemon Lime Love Elixir', 'A love potion of lemon lime tea with popping lychee pearls and lime jelly.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cocoa Crunch Charm', 'Charming cocoa milk tea with a crunch of cocoa cereal clusters and chocolate boba.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Charm Medley', 'An exclusive halal-certified medley featuring a mix of fruity flavors, coconut jelly, and basil seeds.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Classic Espresso', 'A strong and aromatic shot of espresso, perfect for coffee purists.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Vanilla Latte Delight', 'Smooth latte with a hint of sweet vanilla syrup, topped with velvety foam.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Hazelnut Infusion', 'Rich coffee blended with hazelnut syrup, creating a nutty and satisfying experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Chocolate Affogato', 'Halal-friendly version of the Italian classic, featuring chocolate ice cream drowned in a shot of espresso.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Caramel Macchiato Elixir', 'Espresso with steamed milk and a caramel drizzle, creating a sweet and caffeinated delight.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Flat White Harmony', 'A balanced mix of espresso and velvety microfoam, delivering a smooth and creamy texture.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Turmeric Honey Latte', 'A golden latte infused with turmeric and honey, offering a soothing and antioxidant-rich option.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Mocha Madness', 'Indulgent mocha with halal-certified chocolate, topped with whipped cream and chocolate shavings.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Nitro Cold Brew Blitz', 'Smooth and effervescent cold brew coffee infused with nitrogen, providing a refreshing kick.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Matcha Latte Fusion', 'A vibrant blend of matcha and steamed milk, creating a harmonious and antioxidant-rich beverage.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cinnamon Roll Cappuccino', 'Cappuccino with a touch of cinnamon syrup, reminiscent of freshly baked cinnamon rolls.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Coconut Coffee Cooler', 'A tropical twist on iced coffee, featuring coconut milk and halal-certified coffee beans.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Earl Grey Infused Coffee', 'A delicate blend of Earl Grey tea leaves and coffee beans, creating a unique and aromatic fusion.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Almond Joy Latte', 'Latte infused with almond syrup and a hint of coconut, providing a nutty and tropical twist.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Hibiscus Honey Espresso', 'Espresso with a touch of hibiscus and honey, delivering a floral and naturally sweet experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Avocado Espresso Shake', 'Creamy avocado blended with halal espresso, creating a rich and velvety shake.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Brazilian Nut Latte', 'Latte infused with Brazilian nut syrup, creating a creamy and slightly sweet flavor.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Irish Cream Cold Brew', 'Cold brew coffee with a splash of Irish cream syrup, providing a smooth and indulgent experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cardamom Spice Espresso', 'Espresso with a dash of cardamom spice, delivering a fragrant and exotic coffee experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Mango Tango Coffee', 'A tropical coffee blend with mango syrup, offering a fruity and halal-friendly option.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Maple Pecan Latte', 'Latte with the warm flavors of maple syrup and toasted pecans, creating a comforting beverage.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Coconut Mocha Dream', 'Mocha with a coconut milk twist, offering a rich and dairy-free alternative.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Gingerbread Espresso Affogato', 'Espresso poured over gingerbread-flavored ice cream, providing a festive and indulgent treat.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Cherry Blossom Coffee', 'Coffee infused with the delicate essence of cherry blossoms, offering a floral and halal-friendly option.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Turmeric Latte Serenity', 'Latte infused with turmeric, creating a golden and anti-inflammatory beverage.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Rosemary Honey Espresso', 'Espresso with a hint of rosemary and honey, providing a fragrant and soothing coffee option.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cherry Almond Cold Brew', 'Cold brew coffee with cherry and almond flavors, offering a refreshing and subtly sweet drink.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Lavender Vanilla Coffee', 'Coffee infused with the floral notes of lavender and the sweet essence of vanilla, providing a delightful and halal-friendly option.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Ethiopian Yirgacheffe Pour-Over', 'Artisanal pour-over coffee featuring beans from the renowned Ethiopian Yirgacheffe region.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Mexican Chiapas Espresso', 'Espresso with beans sourced from the high-altitude Chiapas region of Mexico, delivering a bold and flavorful experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Panama Geisha Cold Brew', 'Cold brew featuring the rare and prized Panama Geisha beans, known for their unique and complex flavor profile.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Indonesian Sumatra Latte', 'Latte made with halal-certified beans from the lush landscapes of Indonesian Sumatra, offering a rich and full-bodied coffee.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Cascara Sparkling Infusion', 'A bubbly and refreshing coffee drink featuring cascara (coffee cherry) infusion.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Guatemalan Huehuetenango Drip', 'Drip coffee featuring beans from the high-altitude Huehuetenango region of Guatemala, known for their bright acidity.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Orange Zest Cold Brew', 'Cold brew coffee infused with the zest of fresh oranges, offering a citrusy and invigorating experience.');
INSERT INTO foodloop.food(foodName, descriptions) VALUES ('Halal Malaysian Liberica Latte', 'Latte crafted with halal-certified Liberica beans from the tropical landscapes of Malaysia, providing a unique and flavorful coffee.');