INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Flame-Grill House');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Burger Barn');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Grill Master Delight');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Bun & Patty Joint');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Flavor Fusion Grill');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Patty Palace');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('The Burger Joint');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Burger Barons');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Burger Bliss Bistro');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Sizzle Street menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Pasta Paradise Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Twirl & Taste Trattoria Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Italian Delights Ristorante Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Mama Mia Trattoria Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Napoli Finest Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Ristorante Romano Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Trattoria Toscana Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Pasta Pronto Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Bella Italia Bistro Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Nonna Kitchen Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Biryani Boulevard Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Spice Palace Biryani House Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Biryani Delights Express Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Royal Biryani House Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Paradise Biryani Point Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Biryani House of Flavors Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Saffron Spice Biryani Kitchen Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Zafrani Biryani Corner Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Bawarchi Biryani Hub Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Nawabi Biryani House Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Delight');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa King');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Haven');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Lane');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Lagoon');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Lounge');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Land');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Legends');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Lounge Local');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Laksa Village Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Hainanese Delights Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Chicken Rice Express Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Chicky Chicky Rice House Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Chicken Master Kitchen Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Rice 'n' Chicken Haven Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Cluck Cluck Chicken Rice Corner Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Savory Chicken Rice Delight Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Chicken Rice Palace Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Chicken Rice Kingdom Menu');
INSERT INTO foodloop.restaurant(restaurantName) VALUES ('Golden Chicken Rice Corner Menu');
